### ISSUE TITLE
can't find a module confidence-normalization-and-filterting while installing wordlift-stanbol

### ISSUE THREAD

**Issue by mido18** [insideout10/wordlift-stanbol#2]
system: ubuntu 12.04
apache-stanbol status: working
apache stanbol working on http://localhost:8080/ and i'am in wordlift-stanbol directory  i issued the mvn install command i got this error :

 mvn clean install -DskipTests -PinstallBundle -Dsling.url=http://localhost:8080/system/console -o -e
- Error stacktraces are turned on.
  [INFO] 
  NOTE: Maven is executing in offline mode. Any artifacts not already in your local
  repository will be inaccessible.

[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[ERROR] FATAL ERROR
[INFO] ------------------------------------------------------------------------
[INFO] Error building POM (may not be this project's POM).

Project ID: unknown

Reason: Could not find the model file '/home/mido/wordlift-stanbol/confidence-normalization-and-filterting'. for project unknown

[INFO] ------------------------------------------------------------------------
[INFO] Trace
org.apache.maven.reactor.MavenExecutionException: Could not find the model file '/home/mido/wordlift-stanbol/confidence-normalization-and-filterting'. for project unknown
    at org.apache.maven.DefaultMaven.getProjects(DefaultMaven.java:404)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:272)
    at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:138)
    at org.apache.maven.cli.MavenCli.main(MavenCli.java:362)
    at org.apache.maven.cli.compat.CompatibleMain.main(CompatibleMain.java:60)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
    at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
    at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
    at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
Caused by: org.apache.maven.project.ProjectBuildingException: Could not find the model file '/home/mido/wordlift-stanbol/confidence-normalization-and-filterting'. for project unknown
    at org.apache.maven.project.DefaultMavenProjectBuilder.readModel(DefaultMavenProjectBuilder.java:1575)
    at org.apache.maven.project.DefaultMavenProjectBuilder.buildFromSourceFileInternal(DefaultMavenProjectBuilder.java:506)
    at org.apache.maven.project.DefaultMavenProjectBuilder.build(DefaultMavenProjectBuilder.java:200)
    at org.apache.maven.DefaultMaven.getProject(DefaultMaven.java:604)
    at org.apache.maven.DefaultMaven.collectProjects(DefaultMaven.java:487)
    at org.apache.maven.DefaultMaven.collectProjects(DefaultMaven.java:560)
    at org.apache.maven.DefaultMaven.getProjects(DefaultMaven.java:391)
    ... 12 more
Caused by: java.io.FileNotFoundException: /home/mido/wordlift-stanbol/confidence-normalization-and-filterting (No such file or directory)
    at java.io.FileInputStream.open(Native Method)
    at java.io.FileInputStream.<init>(FileInputStream.java:120)
    at hidden.org.codehaus.plexus.util.xml.XmlReader.<init>(XmlReader.java:124)
    at hidden.org.codehaus.plexus.util.xml.XmlStreamReader.<init>(XmlStreamReader.java:67)
    at hidden.org.codehaus.plexus.util.ReaderFactory.newXmlReader(ReaderFactory.java:118)
    at org.apache.maven.project.DefaultMavenProjectBuilder.readModel(DefaultMavenProjectBuilder.java:1570)
    ... 18 more
[INFO] ------------------------------------------------------------------------
[INFO] Total time: < 1 second
[INFO] Finished at: Tue Sep 11 16:17:12 EET 2012
[INFO] Final Memory: 3M/118M
[INFO] ------------------------------------------------------------------------

also from googling it i found this 

ziodave deleted branch confidence-normalization-and-filtering at insideout10/wordlift-stanbol 12 days ago
Deleted branch was at /insideout10/wordlift-stanbol/tree/confidence-normalization-and-filtering

i think there is missing folder or something 
thanks in forward :)

**Comment by ziodave** [comment]
Hello Mohamed,

I removed the reference to confidence-normalization-and-filtering module in the root pom.xml file [commit ff42ecaf82577067b91e1ccab5c08cf7ffc8ed43].

Try now.

David
